<div class="container">
  <h3>¿Esta seguro que desea eliminar este registro?</h3>

  <br><br>

  <?php echo Form::open("", "POST") ?>
    <div class="form-group">
      <label>Tipo cliente</label>
      <?php echo Form::dbSelect('cliente.tipocliente_id', 'nombre', null, 'Seleccione el tipo de cliente', "class='form-control' disabled", $cliente->tipocliente_id ) ?>
    </div>
    <div class="form-group">
      <label>Nit</label>
      <?php echo Form::text('cliente.nit', "class='form-control' readonly", $cliente->nit) ?>
    </div>
    <div class="form-group">
      <label>Nombre</label>
      <?php echo Form::text('cliente.nombre', "class='form-control' readonly", $cliente->nombre) ?>
    </div>
    <div class="form-group">
      <label>Activo</label>
      <?php echo Form::text('cliente.activo', "class='form-control' readonly", $cliente->activo) ?>
    </div>
    <div class="form-group">
      <label>Municipio</label>
      <?php echo Form::dbSelect('cliente.tipomunicipio_id', 'nombre', null, 'Seleccione el municipio', "class='form-control' disabled", $cliente->tipomunicipio_id ) ?>
    </div>
    <div class="form-group">
      <label>Dirección</label>
      <?php echo Form::text('cliente.direccion', "class='form-control' readonly", $cliente->direccion) ?>
    </div>

    <div class="form-group text-right">
      <input type="submit" value="Eliminar" class="btn btn-danger">
      <a href="<?php echo PUBLIC_PATH?>cliente/index" class="btn btn-default">Volver</a>
    </div>
  <?php echo Form::close() ?>
</div>