<?php
function UbicarFilaTipoEnsayo($sheet, $tipoEnsayo)
{
  for ($i=25; $i < 200; $i++) {
    if (trim($sheet->getCell("A$i")->getValue()) == $tipoEnsayo) {
      return $i;
    }
  }

  return null;
}

function cargarReportesDia($formato)
{
  return $formato;
}

function calcularPromedio($sheet, $destSheet, $colIni, $colFin, $fila)
{
  $numItems   = 0;
  $turbiedad  = 0;
  $resultados = array(
    "B" => 0,
    "C" => 0,
    "D" => 0,
    "E" => 0,
    "F" => 0,
    "G" => 0,
    "H" => 0,
    "I" => 0,
    "J" => 0,
    "K" => 0,
    "L" => 0,
    "M" => 0,
    "N" => 0,
    "O" => 0,
    "P" => 0
  );

  $rowTURBIEDAD = UbicarFilaTipoEnsayo($sheet, "TURBIEDAD");
  $rowCOLOR_APARENTE = UbicarFilaTipoEnsayo($sheet, "COLOR APARENTE");

  $rowCONDUCTIVIDAD = UbicarFilaTipoEnsayo($sheet, "CONDUCTIVIDAD ELÉCTRICA");
  $rowALCALINIDAD = UbicarFilaTipoEnsayo($sheet, "ALCALINIDAD TOTAL");
  $rowDUREZA = UbicarFilaTipoEnsayo($sheet, "DUREZA TOTAL");
  $rowpH = UbicarFilaTipoEnsayo($sheet, "PH");
  $rowHIERRO = UbicarFilaTipoEnsayo($sheet, "HIERRO TOTAL");
  $rowCLORUROS = UbicarFilaTipoEnsayo($sheet, "CLORUROS");
  $rowSULFATOS = UbicarFilaTipoEnsayo($sheet, "SULFATOS");
  $rowNITRITOS = UbicarFilaTipoEnsayo($sheet, "NITRITOS");
  $rowCLORO_RESIDUAL = UbicarFilaTipoEnsayo($sheet, "CLORO RESIDUAL");

  $fila += 7;

  $resultados["O"] = 0;
  $resultados["P"] = 10000000;

  for ($i = $colIni; $i <= $colFin ; $i++) {
    $numItems += 1;

    if (isset($rowTURBIEDAD)) { $resultados["B"] += $resultados["B"] + $sheet->getCell($i.$rowTURBIEDAD) ->getValue(); }
    if (isset($rowCOLOR_APARENTE)) { $resultados["C"] += $resultados["C"] + $sheet->getCell($i.$rowCOLOR_APARENTE) ->getValue(); }

    if (isset($rowCONDUCTIVIDAD)) { $resultados["G"] += $resultados["G"] + $sheet->getCell($i.$rowCONDUCTIVIDAD) ->getValue(); }
    if (isset($rowALCALINIDAD)) { $resultados["H"] += $resultados["H"] + $sheet->getCell($i.$rowALCALINIDAD) ->getValue(); }
    if (isset($rowDUREZA)) { $resultados["I"] += $resultados["I"] + $sheet->getCell($i.$rowDUREZA) ->getValue(); }

    if (isset($rowpH)) { $resultados["J"] += $resultados["J"] + $sheet->getCell($i.$rowpH) ->getValue(); }
    if (isset($rowHIERRO)) { $resultados["K"] += $resultados["K"] + $sheet->getCell($i.$rowHIERRO) ->getValue(); }
    if (isset($rowCLORUROS)) { $resultados["L"] += $resultados["L"] + $sheet->getCell($i.$rowCLORUROS) ->getValue(); }
    if (isset($rowSULFATOS)) { $resultados["M"] += $resultados["M"] + $sheet->getCell($i.$rowSULFATOS) ->getValue(); }
    if (isset($rowNITRITOS)) { $resultados["N"] += $resultados["N"] + $sheet->getCell($i.$rowNITRITOS) ->getValue(); }
    if (isset($rowCLORO_RESIDUAL)) {
      $cloroRes = $sheet->getCell($i.$rowCLORO_RESIDUAL) ->getValue();
      $resultados["O"] = $resultados["O"] < $cloroRes ? $cloroRes : $resultados["O"];
      $resultados["P"] = $resultados["P"] > $cloroRes ? $cloroRes : $resultados["P"];
    }
  }

  $resultados["D"] = "ACEPTABLE";
  $resultados["E"] = "ACEPTABLE";
  $resultados["F"] = "AUSENTES";

  foreach ($resultados as $key => $value) {
    if ($key != "D" && $key != "E" && $key != "F" && $key != "O" && $key != "P") {
      $resultados[$key] = $value / $numItems;
    }

    $destSheet->setCellValue("$key$fila", $value);
  }
}

function generarResumen($book)
{
  for ($i=1; $i <=31 ; $i++) {
    if ($book->sheetNameExists("$i")) {
      $currentSheet = $book->getSheetByName("$i");
      $dia          = $i;

      calcularPromedio($currentSheet, $book->getSheetByName('CENTENARIO'), "Q", "T", $i);
      calcularPromedio($currentSheet, $book->getSheetByName('MIJITAYO'), "U", "V", $i);
      calcularPromedio($currentSheet, $book->getSheetByName('SAN FELIPE'), "W", "X", $i);

      $filaIrca = UbicarFilaTipoEnsayo($currentSheet, "IRCA");

      if (isset($filaIrca)) {
        $valor = 0;

        for ($col="Q"; $col <= "X" ; $col++) {
          $valor += $currentSheet->getCell("$col$filaIrca")->getValue();
        }

        $filaIrca = $i + 1;

        $book->getSheetByName("IRCA")
          ->setCellValue("A$filaIrca", $dia)
          ->setCellValue("B$filaIrca", $valor);
      }
    }
  }
}
?>

<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
date_default_timezone_set('America/Bogota');
set_time_limit(0);

if (PHP_SAPI == 'cli')
    die('Este reporte solo se puede ejecutar desde un navegador web');

$objPHPExcel = PHPExcel_IOFactory::load(APP_PATH . '/extensions/formats/promedio_red.xlsx');

$objPHPExcel->getDefaultStyle()->getFont()
        ->setName('Arial')
        ->setSize(16)
        ->setBold(false);

$book = cargarReportesDia($objPHPExcel);
generarResumen($book);

$nombre = 'promedios/promedio.xlsx';

$objWriter = PHPExcel_IOFactory::createWriter($book, 'Excel2007');
$objWriter->save($nombre);
?>
<div class="container">
  <a href="<?php echo PUBLIC_PATH.$nombre ?>" class="btn btn-link">Descargar el reporte</a>
</div>